url: http://trezise.ca
baseurl:
repository: tt--/tt--.github.io

# Site settings
description: "Professional engineer in Ottawa, Canada interested in software and embedded."
title: Tyler Trezise, P.Eng.
title-allcaps: TYLER TREZISE, P.Eng.
# og-image: /img/og-image.jpg
og-image: /img/header-bg.jpg

email: https://mailhide.io/e/dy8cV

collections:
- projects

# Team names, titles and social links
people:
- name: Tyler Trezise, P.Eng.
  pic:
  position:
  social:
  - title: linkedin
  url: http://ca.linkedin.com/in/tylertrezise

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# refer to: http://fontawesome.io/icons/
social-contact:
  - icon: envelope
    title: Send me an email
    url: https://mailhide.io/e/dy8cV
  - icon: linkedin
    title: LinkedIn profile
    url: http://ca.linkedin.com/in/tylertrezise
  - icon: skype
    title: "Skype: tylert7"
    url: skype:tylert7?call

social-footer:
  - title: Google Scholar profile
    url: https://scholar.google.com/citations?user=PxUZ8YQAAAAJ
    icon: ai-google-scholar
    icontype: ai
  - title: Stack Overflow profile
    url: http://stackoverflow.com/users/3066295/tt?tab=profile
    icon: fa-stack-overflow
    icontype: fa
  - title: GitHub profile
    url: https://github.com/TT--
    icon: fa-github
    icontype: fa
  - title: HackerRank
    url: https://www.hackerrank.com/__T__
    iconimgsrc: HackerRank_logo.svg
    iconimgalt: HackerRank profile

# Postal address (add as many lines as necessary)
address:
  - line: Ottawa
  - line: Canada

# Build settings
markdown: kramdown
permalink: pretty

# Gems
# https://help.github.com/articles/emoji-on-github-pages/
plugins:
  - jemoji
