url: http://trezise.ca
baseurl: 
repository: tt--/tt--.github.io

# Site settings
description: "Tyler Trezise: Professional engineer in Ottawa Canada interested in embedded and mobile development."
title: Tyler Trezise, P.Eng.
title-allcaps: TYLER TREZISE, P.Eng.

email: http://www.google.com/recaptcha/mailhide/d?k=01Fqo5M4sCOuHDBWiglleMWQ==&c=9dTla-ArGgmyk4CgVqhCG_6c0hHHLmtxC53H-Ftk7lY=

collections:
- projects

# Team names, titles and social links
people:
- name: Tyler Trezise
  pic:
  position:
  social:
  - title: linkedin
  url: http://ca.linkedin.com/in/tylertrezise

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# refer to: http://fontawesome.io/icons/
social-contact:
  - title: envelope
    url: http://www.google.com/recaptcha/mailhide/d?k=01Fqo5M4sCOuHDBWiglleMWQ==&c=9dTla-ArGgmyk4CgVqhCG_6c0hHHLmtxC53H-Ftk7lY=
  - title: linkedin
    url: http://ca.linkedin.com/in/tylertrezise
  - title: skype
    url: skype:tylert7?call

social-footer:
  - title: stack-overflow
    url: http://stackoverflow.com/users/3066295/tt?tab=profile
    icon: fa-stack-overflow
  - title: github
    url: https://github.com/TT--
    icon: fa-github
  - title: HackerRank
    url: https://www.hackerrank.com/__T__
    iconimgsrc: HackerRank_logo.svg
    iconimgalt: HackerRank logo

# Postal address (add as many lines as necessary)
address:
  - line: Ottawa, ON
  - line: Canada

# Build settings
markdown: kramdown
permalink: pretty

# Gems
# https://help.github.com/articles/emoji-on-github-pages/
gems:
  - jemoji